version: "3"

services:
  db:
    container_name: postgres
    image: postgres:13.3
    environment:
      PGDATA: /data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/data