export const ARTICLE_NAVIGATION_TYPE = {
  ARTICLE: 'ARTICLE',
  AUTHOR: 'AUTHOR',
  TAGS: 'TAGS',
  EDIT: 'EDIT',
} as const;

export type ARTICLE_NAVIGATION_TYPE = typeof ARTICLE_NAVIGATION_TYPE[keyof typeof ARTICLE_NAVIGATION_TYPE];
