export const MAIN_NAVIGATION_TYPE = {
  SPLASH: 'SPLASH',
  MAIN: 'MAIN',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  HOME: 'HOME',
  FEED: 'FEED',
  POST_ARTICLE: 'POST_ARTICLE',
  MY: 'MY',
} as const;

export type MAIN_NAVIGATION_TYPE = typeof MAIN_NAVIGATION_TYPE[keyof typeof MAIN_NAVIGATION_TYPE];
