http:
  host: 'http://localhost'
  port: 8080
jwt:
  access-token:
    secret: ACCESS_TOKEN_SECRET_TEST
    expiration-time: 1800000 # 1000*60*30
  refresh-token:
    secret: REFRESH_TOKEN_SECRET_TEST
    expiration-time: 604800000 # 1000*60*60*24*7
